### ISSUE TITLE
error save when button on create/update

### ISSUE THREAD

**Issue by adityadees** [sietse85/nova-button#5]
![image](https://user-images.githubusercontent.com/37553901/172044861-10122552-1c97-455b-88bf-b84f670b437a.png)

` Button::make('Preview')->style('warning')->link(route('blog_preview') . '?id=' . $this->posts_id)
                ->showOnCreating()->showOnUpdating(),`

Why I cannot save if I use ` ->showOnCreating()->showOnUpdating(),` ?

**Comment by sietse85** [comment]
@adityadees can you check your console for errors?

**Comment by adityadees** [comment]
I've check it on console and also on fetch/xhr there's no error
may you can check it? just need to add `->showOnCreating()->showOnUpdating()` then the form won't submit

but if you remove that, you can submit the form

**Comment by sietse85** [comment]
@adityadees  I suspect the problem is that Nova tries to treat the button as a field when you enable it on the forms. There is a reason the `Button.php` script sets these 2 fields to false by default. You cannot use the Buttons on edit/create forms because of Nova default behaviour. I cannot think of a way to workaround this, maybe someone else can. On Index / Detail view you should have no problems.

**Comment by adityadees** [comment]
yeah, I just following the documentation using` showOnCreating` and `showOnUpdating`. Are on Nova3 this working fine?

**Comment by sietse85** [comment]
No it will not work in any version of Nova.
